---
# tasks file for lighthouse
# Подготовка, pre tasks
- name: Lighthouse -> install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present
# install nginx
- name: Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: NGINX -> install Nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: Start nginx
- name: NGINX | Create general config
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: Reload nginx
  
# install lighthouse
- name: 'Lighthouse -> github'
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_src }}"
    version: master
    dest: "{{ lighthouse_dir }}"
  notify: Get lighthouse GIT
- name: 'lighthouse -> nginx config'
  become: true
  ansible.builtin.template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: Restart nginx service
