---
# handlers file for lighthouse
# Start nginx service
- name: Start nginx service
  become: true
  command: nginx
# Reload nginx service
- name: Reload nginx service
  become: true
  command: nginx -s reload
